#
# DO NOT EDIT THIS FILE DIRECTLY - UNLESS YOU KNOW WHAT YOU ARE DOING
#

user node[:spark_terasort][:user] do
  action :create
  supports :manage_home => true
  home "/home/#{node[:spark_terasort][:user]}"
  shell "/bin/bash"
  not_if "getent passwd #{node[:spark_terasort]['user']}"
end

group node[:spark_terasort][:group] do
  action :modify
  members ["#{node[:spark_terasort][:user]}"]
  append true
end


private_ip = my_private_ip()
public_ip = my_public_ip()



# Pre-Experiment Code


# Configuration Files


